Mike welcome
reactivepixel/Max-Bot pull request #111
Opened 2018-03-04 19:31 UTC by MikeSewell

Updated readme and added the welcome new users feature

2018-03-04 22:12 UTC, krogers78 commented
Everything looks good. My one suggestion would be to maybe utilize the variable inside your function for the welcome message to personalize the welcome message, but if not then everything looks good!

2018-03-05 01:06 UTC, LevanceWam commented
Hey mike code looks good I would add some more comments and for your controller name for your welcome file I would name that a little differently its bland and can easily confuse others. besides that Good code.

2018-03-05 01:33 UTC, MikeSewell commented
@krogers78 That's a good idea, I didn't think about adding the name to the message that would be a good way to use the `this` in the method.

2018-03-12 20:17 UTC, reactivepixel requested changes
Overall very good implementation, but you fall short of this code being ready for release due to the controller not being called / implemented in client.js

2018-03-12 20:17 UTC, reactivepixel commented on bot/controllers/newUsers.js
> +      new Command('!welcome', '!welcome', 'Welcome Message', 'Sends a new user of the channel the welcome message', this.msgNewUserWelcome.bind(controller), 'dm'),
Your implementation is deviating from in the formatting from the other established controllers.

2018-03-12 20:17 UTC, reactivepixel commented on bot/client.js
> +  member.sendMessage('Welcome to the channel!');
Consider that your implementation solves the problem, and elegantly, but falls just short in that your solution ​within the client.js file does not implement the controller you created. So in effect, any further maintenance will require duplicate efforts in keeping both messages identical.

2018-03-12 20:17 UTC, reactivepixel commented on readme.md
> +[code] to call a log()
Good catch.

2018-05-04 13:42 UTC, closed without merging