Welcome func_Wamley
reactivepixel/Max-Bot pull request #114
Opened 2018-03-05 00:52 UTC by LevanceWam

Created a welcome functionality that will message the user when they first enter the server and when they hit the command !welcome.

2018-03-05 02:21 UTC, BHess2653 commented
LGTM!

2018-03-05 02:31 UTC, krogers78 commented
Looks good! I like the use of the username to personalize the message for each user!

2018-03-12 20:22 UTC, reactivepixel requested changes
Not ready to deploy as is. Spelling errors that are exposed to the user are not ideal.

Additionally, the controller issue will prevent this from being implemented in actuality.

2018-03-12 20:22 UTC, reactivepixel commented on bot/client.js
> +  member.sendMessage(`Hey ${member.user.username} welcome to the server.`);
Consider that your implementation solves the problem, and elegantly, but falls just short in that your solution ​within the client.js file does not implement the controller you created. So in effect, any further maintenance will require duplicate efforts in keeping both messages identical.

2018-03-12 20:22 UTC, reactivepixel commented on bot/controllers/welcome.js
> +        'Resend the welcome message you recieved when you joined the server.',
Spelling Error

2018-03-12 20:22 UTC, reactivepixel commented on bot/controllers/welcome.js
> +    return `Welcome to the server, ${message.author.username}`;
This message differs from the actual welcome message, so this is not actually a resending of that message. ITs these small deviation, combined with the help message that you are defining this as how you 'resend' that message that will confuse users.

2018-05-04 13:42 UTC, closed without merging