Welcome hess
reactivepixel/Max-Bot pull request #115
Opened 2018-03-05 02:10 UTC by BHess2653

2018-03-05 02:13 UTC, LevanceWam commented
Looked over your code and everything looks ready to go

2018-03-05 03:11 UTC, MikeSewell approved these changes
Looks good to me!

2018-03-12 20:25 UTC, reactivepixel requested changes
Not ready to deploy as is. Spelling errors that are exposed to the user are not ideal.

Additionally, the controller issue will prevent this from being implemented in actuality.

2018-03-12 20:25 UTC, reactivepixel commented on bot/client.js
> +  member.sendMessage(`${member.user.username}, Welcome to the Full Sail Armada! Enjoy your stay! and use !help to see list of commands!`);
Consider that your implementation solves the problem, and elegantly, but falls just short in that your solution ​within the client.js file does not implement the controller you created. So in effect, any further maintenance will require duplicate efforts in keeping both messages identical.

2018-03-12 20:25 UTC, reactivepixel commented on bot/controllers/welcome.js
> +        'Replay welcome message recieved when you join the server.',
Spelling Error

2018-05-04 13:42 UTC, closed without merging