Feature rewards system
reactivepixel/Max-Bot pull request #131
Opened 2018-03-16 01:06 UTC by krogers78

This feature will allow users to earn points for chatting on the server, general activity like streaming, gaming, etc, and inviting new users to join the server. Along with that, admins are able to use a command to return a list of users with the most points sorted highest to lowest.

2018-03-16 01:29 UTC, MikeSewell requested changes
There should be some documentation letting the user know about the new rewards system.

2018-03-16 02:37 UTC, krogers78 commented
Looks good to me! Love the addition of the usage for the new feature.

2018-03-16 03:06 UTC, BHess2653 commented
Looks good to me

2018-03-16 03:15 UTC, drubiodev commented
Looks good

2018-03-16 15:52 UTC, MikeSewell approved these changes

2018-03-16 18:04 UTC, reactivepixel requested changes

2018-03-16 18:04 UTC, reactivepixel commented on bot/client.js
> +    const memberData = await Member.findAll({
Over usage of await

2018-03-16 18:04 UTC, reactivepixel commented on bot/client.js
> +// oldMember is required due to documentation
Add a url to the specific docs that are an issue.

2018-03-16 18:04 UTC, reactivepixel commented on bot/client.js
> +  !game ? getUserPointsandUpdate(id, 5) : null;
Magic number has no context

2018-03-16 18:04 UTC, reactivepixel commented on bot/controllers/invite.js
> +    const validDomains = ['student.fullsail.edu', 'fullsail.edu', 'fullsail.com'];
Not dry add to the util.

2018-03-16 18:04 UTC, reactivepixel commented on bot/controllers/invite.js
> +    const email = message.parsed[1].toLowerCase();
Validate the email address is valid

2018-03-16 18:04 UTC, reactivepixel commented on bot/controllers/invite.js
> +      if (err)util.log('create invite err : ', err, 3);
Should abort processing of this function if err

2018-03-16 18:04 UTC, reactivepixel commented on bot/controllers/invite.js
> +            message.author.send('you have sent the invite');
Sentences start with Capitals and end with punctuation.

2018-03-16 18:04 UTC, reactivepixel commented on bot/controllers/invite.js
> +    return 'You have received 1 point';
Variable, not a string of 1

2018-03-16 18:04 UTC, reactivepixel commented on bot/controllers/topUsers.js
> +        '!topUsers <Limit_Wanted>',
Consider another phrase, number_of_users

2018-03-16 18:04 UTC, reactivepixel commented on bot/controllers/topUsers.js
> +        const fullMessage = results.map(element =>
element is generic

2018-03-16 18:04 UTC, reactivepixel commented on bot/controllers/verify.js
> +              points: 0,
Check existing logic for what happens in the event a user double verifies.

Ideally you don't want to wipe points out due to user ignorance.

2018-03-16 18:38 UTC, krogers78 commented
Hey guys, I'm going to remove any trace of the messagesCount, add the welcome command, and create a `isVerified` util function.

2018-03-16 18:49 UTC, LevanceWam commented
Hey guys I am going to move the valid domains, make spelling and punctuation , and validating that the email is valid.

2018-03-16 18:50 UTC, BHess2653 commented on bot/client.js
> +  !game ? getUserPointsandUpdate(id, 5) : null;
I will update this with a link to the docs about oldMember and newMember and give context to the magic number.

2018-03-16 18:51 UTC, BHess2653 commented
Hey guys I am going to fix the magic number and add docs to oldMember at the bottom of client.js

2018-03-16 21:40 UTC, krogers78 commented on bot/controllers/topUsers.js
> +        '!topUsers <Limit_Wanted>',
I will make sure to give this more context!

2018-03-16 21:41 UTC, krogers78 commented on bot/controllers/topUsers.js
> +        const fullMessage = results.map(element =>
Definitely will give this a new name to better suit the data.

2018-03-16 21:42 UTC, krogers78 commented on bot/controllers/verify.js
> +              points: 0,
After checking the logic in this file, trying to verify for a second time will not reset their points. Logic is in place to ensure that users cannot be created twice.

2018-03-19 03:07 UTC, krogers78 commented on bot/client.js
> +// oldMember is required due to documentation
This has been added although the comment has not collapsed.

2018-05-04 13:42 UTC, closed without merging