!welcome by Hess
reactivepixel/Max-Bot pull request #145
Opened 2018-05-07 06:44 UTC by BHess2653

!welcome command.

sends welcome message to new users and a message to the general chat.
use !welcome to resend the welcome message.

2018-05-07 22:45 UTC, brennondenny commented
Everything works fine for me, maybe consider changing the welcome command to !tos or change it's description in the help menu to say it is sending the tos since that's the main reason a user would use that command.

2018-05-07 22:46 UTC, mattpezzente commented on bot/client.js
> +  member.sendMessage(`${member}, Welcome to the Full Sail Armada! These are the terms of service...`);
Small detail, but consider lower-casing the "W" in "Welcome" as it comes after a comma

2018-05-07 22:51 UTC, mattpezzente commented on bot/client.js
> +  member.sendMessage(`${member}, Welcome to the Full Sail Armada! These are the terms of service...`);
Also, "sendMessage" is being deprecated, so it is recommended to change those methods to just "send".

2018-05-07 22:52 UTC, mattpezzente requested changes
See comments on commit, some deprecation changes should be made.

2018-05-07 23:01 UTC, brennondenny requested changes
Add in the default comments found across the controllers to your welcome.js file.

2018-05-07 23:01 UTC, brennondenny commented on bot/controllers/welcome.js
> +
Add in the default comments found across the controllers to your welcome.js file.

2018-05-08 01:03 UTC, brennondenny approved these changes

2018-05-08 16:33 UTC, mattpezzente approved these changes

2018-05-08 17:53 UTC, reactivepixel requested changes
Very good work incorporating the feedback from your peers in shaping this submission. Ideally, I would have like you to solve the duplicate code logic issue out of the gate, but all submissions seem to have missed this, and we will discuss this further on Wednesday. The idea there would be to invoke the controller you have built rather than manually sending a message in the guildadduser event. Either way, solid work!

2018-05-08 17:53 UTC, reactivepixel commented on bot/client.js
> +  if (!channel) return;
This is a non-intuitive way to 'do nothing'.

2018-05-08 17:53 UTC, reactivepixel commented on bot/client.js
> +  member.send(`${member}, Welcome to the Full Sail Armada! These are the terms of service...`);
Duplicate logic in your controller.

2018-05-08 17:53 UTC, reactivepixel commented on bot/client.js
> +  channel.send(`Welcome to the Full Sail Armada ${member}! for more information use !help`);
The announcement to the general channel should not have a !help cmd reminder. This should be in the welcome message if anywhere.

2018-05-08 17:53 UTC, reactivepixel commented on bot/controllers/welcome.js
> +        'Resends terms of service message.',
Good phrasing on your help message

2018-06-05 01:19 UTC, closed without merging