Dynamic Event Controllers to Handle Multiple Event Types
reactivepixel/Max-Bot pull request #159
Opened 2018-05-18 12:00 UTC by mattpezzente

Hey everyone, I will need a bunch of feed back on this approach to creating a dynamic event controller if possible.

I've tackled this issue by separating the messaging and event aspects of Max-Bot. This structure pretty much allows new developers to take the following steps whenever they make a new event:

#### Steps:

1. Define the event in client.js.

2. Create an Event Controller in the "event" folder.

3. Configure the Event by adding in as many actions to fire as desired.

#### Feedback:

I will be continuing work on this throughout the day, and possibly even into the next release, as I would like this to be as clean and efficient as possible. I need your feedback on what you think of this process, any ways to simplify, and any potential flaws that you may see with this.

2018-05-18 22:22 UTC, brennondenny requested changes

2018-05-18 22:22 UTC, brennondenny commented on bot/client.js
> +// Listen for messages
Any event created on a message doesn't seem to be working correctly.

2018-05-18 22:22 UTC, brennondenny commented on bot/events/guildMemberAdd.js
> +module.exports = GuildMemberAddEvent;
This action works but breaks when other events are added in. I also found that sometimes I would get a second "Hello" message after the "MUAHAHAHAHAHAAHAHA" but I could not pinpoint to why this would be happening

2018-05-19 03:44 UTC, brennondenny approved these changes

2018-05-19 03:48 UTC, mpeck99 commented
It seems that you have some conflicts in our channel.js and roles.js I think that some extra code has been added

2018-05-19 03:52 UTC, JATaber commented
The conflicts issue seems to be happening to a few people tonight. Is there anyone that would know why this is going on?

2018-05-19 04:21 UTC, mattpezzente commented
Since this pull request will be on going for Release 3, the merge conflicts will be put on hold.

2018-05-21 17:50 UTC, mattpezzente commented
I have updated the controllers to now work with almost any event we would like to generate.

#### Steps for implementing a new event

1. Add the event to the Client.js
```
// bot/client.js

// Create an event listener for new guild members
client.on('eventName', (member) => {
  controllerPicker('eventName', member);
});
```

2. Create a new controller in the "controllers" folder, with the following naming convention:
*eventName.js*

3. Start the controller with the following template:
```
// bot/controllers/eventName.js

const BaseController = require('../baseController.js');
const Event = require('../baseEvent.js');

class EventNameController extends BaseController {
  constructor(member) {
    super(member);
    const controller = this;
    // Name of event to trigger this controller
    this.eventName = 'eventName';
    // Array of Events to fire
    this.events = []
}

module.exports = EventNameController;
```

4. Create an Event, and add it to the constructor:
```
// bot/controllers/eventName.js

const BaseController = require('../baseController.js');
const Event = require('../baseEvent.js');

class EventNameController extends BaseController {
  constructor(member) {
    super(member);
    const controller = this;
    this.eventName = 'guildMemberAdd';
    // Array of Events to fire
    this.events = [
      new Event(
        this.event = 'eventName',
        this.name = 'ExampleEventName',
        this.description = 'This is an example event description',
        this.action = this.doSomething.bind(controller),
      ),
    ];
  }
}

module.exports = EventNameController;

5. Lastly, create a function to fire
```
// bot/controllers/eventName.js

const BaseController = require('../baseController.js');
const Event = require('../baseEvent.js');

class EventNameController extends BaseController {
  constructor(member) {
    super(member);
    const controller = this;
    this.eventName = 'guildMemberAdd';
    // Array of Events to fire
    this.events = [
      new Event(
        this.event = 'eventName',
        this.name = 'ExampleEventName',
        this.description = 'This is an example event description',
        this.action = this.doSomething.bind(controller),
      ),
    ];
  }
  doSomething() {
    const { eventObj } = this;
    return eventObj;
  }
}

module.exports = EventNameController;

2018-05-21 23:31 UTC, brennondenny requested changes

2018-05-21 23:31 UTC, brennondenny commented on bot/controllers/message.js
> +    return eventObj.reply(helpString);
!help command tags users twice

2018-05-21 23:32 UTC, brennondenny commented
Other than the review above, I was able to implement my welcome feature, and !question feature flawlessly.

2018-05-22 00:35 UTC, mattpezzente commented
Double user tagging fixed.

2018-05-22 01:40 UTC, brennondenny approved these changes

2018-05-22 02:30 UTC, mpeck99 commented
Looks good overall everything works on my end.

2018-05-22 02:46 UTC, merged