Multi-language support
reactivepixel/Max-Bot pull request #163
Opened 2018-05-21 16:41 UTC by BHess2653

currently uses English(en), Spanish(es), and Alien(al).

.env example: LANGUAGE=en

messages are located in bot/locale/messages.json sorted by controllers.

2018-05-21 22:53 UTC, BHess2653 commented
Ready for Review and Release 3!

2018-05-21 23:39 UTC, brennondenny commented
en, es, and al are all working with every command, If it's in the scope add a check in case the users defined LANGUAGE in the .evn is available.

Other than that your good to merge! 👍

2018-05-22 01:28 UTC, mattpezzente requested changes
Make sure to implement the default fallback in-case the LANGUAGE is not set int he .env, or incase an incorrect LANGUAGE is set.

2018-05-22 01:28 UTC, mattpezzente commented on bot/controllers/channels.js
> +const lang = process.env.LANGUAGE;
Make a provision for setting the default language to en, incase no language is set in the .env.

2018-05-22 01:28 UTC, mattpezzente commented on bot/controllers/verify.js
>  }
Make sure to default all languages to en. If none are set, or if an incorrect langauge is set, all messages appear as *underfined* in Discord.

2018-05-22 01:48 UTC, mpeck99 commented
Besides the changes requested above overall looks good!

2018-05-22 03:21 UTC, BHess2653 commented
Changes have been made default Language is now en!

2018-05-22 03:58 UTC, mattpezzente approved these changes

2018-05-22 04:58 UTC, brennondenny commented
Looks like CircleCL found some ESLint Issues.

2018-05-22 05:03 UTC, merged